### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by achingbrain**
I've got quite a lot of copies of Wreck in my node_modules folder - this means that a lot of [good](https://github.com/hapijs/good) logging doesn't occur because Wreck is a singleton.

This PR updates all h2o2 dependencies to the latest versions (including Wreck 7) and fixes some linting complaints that code had after the upgrade.

I hope you'll consider merging this, happy to make whatever amends are necessary.

### CODE REVIEW

**Comment by Marsup** [comment]
We have a no ^ policy in this org.

**Comment by osukaa** [comment]
I'll be publishing a new version tonight :)

**Comment by achingbrain** [comment]
Great, thanks!

**Comment by osukaa** [comment]
@achingbrain hi! It's published :)

**Pull request merged**
