### PR TITLE
Remove new Buffer usage

### PR DESCRIPTION
**Pull request by Marsup**

### CODE REVIEW

**Comment by spanditcaa** [comment]
@Marsup this would require node 5.10.0 minimum.  That is fine for hapi 17/master here but since hapi 16 specifies >=4.8.0 in the package.json and the 6.x branch of h2o2 allows node >4, I'll also add this to the 6.x branch and set the min node version there to 5.1.0.

**Comment by Marsup** [comment]
I'm not sure it's necessary to backport, especially considering it's only in the unit tests.

**Comment by AdriVanHoudt** [comment]
I don't think a backport is needed for this simple test change idd

**Comment by spanditcaa** [comment]
So I should actually look at the file that changed in the PR as well as the code itself ??

**Comment by Marsup** [comment]
I don't get the question.

**Comment by AdriVanHoudt** [comment]
`this was a poor attempt at humor ` :P

**Pull request merged**
